name: Issue sync (GitHub -> Codeberg)
on:
  issues:
    types: [opened, deleted, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]
  issue_comment:
    types: [created]

jobs:
  issue_sync:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub -> Codeberg Issue sync
        run: |
          URL="https://codeberg.org/"
          REPO="ethical_haquer/mirror-test"
          TOKEN=${{ secrets.GIT_TOKEN }}

          sync=0

          echo "Issue body: ${{ github.event.issue.body }}"
          echo "Comment body: ${{ github.event.comment.body }}"
          echo "Event Name: ${{ github.event_name }}"

          ##### Issue #####
          if [ "${{ github.event_name }}" == 'issues' ]; then
            if [[ "${{ github.event.issue.body }}" == "<p><table><tr><th><details><summary></summary>This is an issue created by automatic synchronization.</details>"* ]]; then
              echo "Already synchronized - nothing to do"
              sync=1
            else
              data="{\"title\": \"${{ github.event.issue.title }}\", \"body\": \"<p><table><tr><th><details><summary></summary>This is an issue created by automatic synchronization.</details></th><th><a href='https://github.com/${{ github.event.issue.user.login }}'><img src='https://github.com/${{ github.event.issue.user.login }}.png' width='25'></a></th><th><a href='https://github.com/${{ github.event.issue.user.login }}'>${{ github.event.issue.user.login }}</a> commented on GitHub</th><th><a href='https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }}'>Link to the issue</a></th></tr></table></p>${{ github.event.comment.body }}\"}"
              url=$URL"api/v1/repos/"$REPO"/issues"
            fi

          ##### Issue comment #####
          elif [ "${{ github.event_name }}" == 'issue_comment' ]; then
            if [[ "${{ github.event.comment.body }}" == "<p><table><tr><th><details><summary></summary>This is an issue created by automatic synchronization.</details>"* ]]; then
              echo "Already synchronized - nothing to do"
              sync=1
            else
              echo "Creating Issue Comment"
              data="{\"title\": \"Issue-Comment\", \"body\": \"<p><table><tr><th><details><summary></summary>This is an issue created by automatic synchronization.</details></th><th><a href='https://github.com/${{ github.event.comment.user.login }}'><img src='https://github.com/${{ github.event.comment.user.login }}.png' width='25'></a></th><th><a href='https://github.com/${{ github.event.comment.user.login }}'>${{ github.event.comment.user.login }}</a> commented on GitHub</th><th><a href='https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }}'>Link to the issue</a></th></tr></table></p>${{ github.event.comment.body }}\"}"
              url=$URL"api/v1/repos/"$REPO"/issues/${{ github.event.issue.number }}/comments"
            fi
          fi

          if [[ $sync == 1 ]]; then
            echo "curl --> Already synchronized"
          else
            curl -X POST -H "Authorization: token $TOKEN" -H "Content-Type: application/json" -d "$data" $url
          fi          
